dist: Bionic
language: node_js
node_js:
  - 14
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - git submodule update
  - cd hexo
  - npm install
  - sed -i "s#%WWW_BLOG_DEPLOY_TOKEN%#$WWW_BLOG_DEPLOY_TOKEN#" _config.yml
  - hexo clean && hexo deploy
