# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: '观澜'
subtitle: '行到水穷处，坐看云起时'
description: ''
keywords:
author: 'Amos'
language: 'zh-CN'
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://amos.s2u2m.com
root: /
permalink: :year/:month/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
# NexT theme config
theme_config:
  avatar:
    # Replace the default image and set the url here.
    url: /images/avatar.jpeg
    # If true, the avatar will be dispalyed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: true
  footer:
    copyright: s2u2m
    beian:
      enable: true
      icp: 蜀ICP备18013492号
  darkmode: false
  scheme: Pisces
  language: zh-Hans
  menu:
    home: / || fa fa-home
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
    #schedule: /schedule/ || calendar
    # sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat
  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true
    language: zh-Hans
  social:
    E-Mail: mailto:xiayy860612@126.com || fa fa-envelope
    GitHub: https://github.com/xiayy860612 || fa fa-github
  local_search:
    enable: true
  search:
    path: search.xml
    field: post
    format: html
    limit: 100
  # busuanzi_count:
  #   enable: true
  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
  related_posts:
    enable: true
    title: # Custom header, leave empty to use the default one
    display_in_home: true
    params:
      maxCount: 5
  vendors:
    # fontawesome: https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.2/css/all.min.css
    valine: https://unpkg.com/valine/dist/Valine.min.js
  valine:
    enable: true
    appid: YnmrykAQHQwGzUR77I61DkKN-9Nh9j0Va
    appkey: 4TzKa97Pz2JTg81B8o5l77mO
    placeholder: 一起来聊一聊呗
    avatar: retro
    guest_info: nick,mail
    pageSize: 10 # Pagination size
    visitor: true # Article reading statistic
    comment_count: true # If false, comment count will only be displayed in post page, not in home page
    recordIP: true # Whether to record the commenter IP
  
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: false
plantuml:
  #  Local or PlantUMLServer.
  render: "PlantUMLServer"
  # the server,you can change your self-hosted sever for privacy
  server: "http://www.plantuml.com/plantuml"
  # "inline": <svg>xxx<svg/>
  # "inlineUrlEncode": <img src='data:image/svg+xml;>
  # "inlineBase64": <img src='data:image/svg+xml;base64>
  # "localLink": <img src="/assert/puml/xxxx.svg">
  # "externalLink": <img src="http://www.plantuml.com/plantuml/svg/xxx">
  link: "inline"
  # common options: svg/png
  outputFormat: "svg"

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 'https://%WWW_BLOG_DEPLOY_TOKEN%@github.com/xiayy860612/www.git'
  branch: blog

