name: Deploy Hexo Blog

on:
  push:
    branches: [hexo]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1
          sparse-checkout: |
            /*
            !/achieve/*
            !/examples/*
          sparse-checkout-cone-mode: false
      # Install pandoc
      - name: Install pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        working-directory: blog
        run: npm ci
      - name: Deploy Pages
        working-directory: blog
        run: |
          npm run clean
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: blog/public

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4